
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded for private deployment
const SUPABASE_URL = 'https://mjaxvbvgkgnfsmlghdke.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qYXh2YnZna2duZnNtbGdoZGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTYxNTcsImV4cCI6MjA2Mjk3MjE1N30.dhHwe070VW90tFRJwroB2Dl45b3MGo7XbaBT84GepAw';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
